/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.junit.jupiter.api.Test;
//import org.junit.Test;
//import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class LibraryTest {
    @Test 
    public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue( classUnderTest.someLibraryMethod(),
    "\"someLibraryMethod should return 'true'\"");
    }
}
